"""Generate data/countries.json roster with flag emojis."""
from __future__ import annotations

import json
from pathlib import Path


def flag(iso: str) -> str:
    iso = iso.upper()
    if len(iso) != 2 or not iso.isalpha():
        return "\U0001f3f3\ufe0f"
    return "".join(chr(0x1F1E6 + ord(c) - ord("A")) for c in iso)


# id, name, iso_a2, adm0_a3, ne_names
COUNTRIES: list[tuple] = [
    ("AF", "Afghanistan", ["AF"], ["AFG"], ["Afghanistan"]),
    ("AL", "Albania", ["AL"], ["ALB"], ["Albania"]),
    ("DZ", "Algeria", ["DZ"], ["DZA"], ["Algeria"]),
    ("AD", "Andorra", ["AD"], ["AND"], ["Andorra"]),
    ("AO", "Angola", ["AO"], ["AGO"], ["Angola"]),
    ("AG", "Antigua and Barbuda", ["AG"], ["ATG"], ["Antigua and Barbuda"]),
    ("AR", "Argentina", ["AR"], ["ARG"], ["Argentina"]),
    ("AM", "Armenia", ["AM"], ["ARM"], ["Armenia"]),
    ("AU", "Australia", ["AU"], ["AUS"], ["Australia"]),
    ("AT", "Austria", ["AT"], ["AUT"], ["Austria"]),
    ("AZ", "Azerbaijan", ["AZ"], ["AZE"], ["Azerbaijan"]),
    ("BS", "Bahamas", ["BS"], ["BHS"], ["Bahamas"]),
    ("BH", "Bahrain", ["BH"], ["BHR"], ["Bahrain"]),
    ("BD", "Bangladesh", ["BD"], ["BGD"], ["Bangladesh"]),
    ("BB", "Barbados", ["BB"], ["BRB"], ["Barbados"]),
    ("BY", "Belarus", ["BY"], ["BLR"], ["Belarus"]),
    ("BE", "Belgium", ["BE"], ["BEL"], ["Belgium"]),
    ("BZ", "Belize", ["BZ"], ["BLZ"], ["Belize"]),
    ("BJ", "Benin", ["BJ"], ["BEN"], ["Benin"]),
    ("BT", "Bhutan", ["BT"], ["BTN"], ["Bhutan"]),
    ("BO", "Bolivia", ["BO"], ["BOL"], ["Bolivia"]),
    ("BA", "Bosnia and Herzegovina", ["BA"], ["BIH"], ["Bosnia and Herz."]),
    ("BW", "Botswana", ["BW"], ["BWA"], ["Botswana"]),
    ("BR", "Brazil", ["BR"], ["BRA"], ["Brazil"]),
    ("BN", "Brunei", ["BN"], ["BRN"], ["Brunei"]),
    ("BG", "Bulgaria", ["BG"], ["BGR"], ["Bulgaria"]),
    ("BF", "Burkina Faso", ["BF"], ["BFA"], ["Burkina Faso"]),
    ("BI", "Burundi", ["BI"], ["BDI"], ["Burundi"]),
    ("CV", "Cabo Verde", ["CV"], ["CPV"], ["Cabo Verde"]),
    ("KH", "Cambodia", ["KH"], ["KHM"], ["Cambodia"]),
    ("CM", "Cameroon", ["CM"], ["CMR"], ["Cameroon"]),
    ("CA", "Canada", ["CA"], ["CAN"], ["Canada"]),
    ("CF", "Central African Republic", ["CF"], ["CAF"], ["Central African Rep."]),
    ("TD", "Chad", ["TD"], ["TCD"], ["Chad"]),
    ("CL", "Chile", ["CL"], ["CHL"], ["Chile"]),
    ("CN", "China", ["CN"], ["CHN"], ["China"]),
    ("CO", "Colombia", ["CO"], ["COL"], ["Colombia"]),
    ("KM", "Comoros", ["KM"], ["COM"], ["Comoros"]),
    ("CG", "Congo", ["CG"], ["COG"], ["Congo"]),
    ("CD", "DR Congo", ["CD"], ["COD"], ["Dem. Rep. Congo"]),
    ("CR", "Costa Rica", ["CR"], ["CRI"], ["Costa Rica"]),
    ("HR", "Croatia", ["HR"], ["HRV"], ["Croatia"]),
    ("CU", "Cuba", ["CU"], ["CUB"], ["Cuba"]),
    ("CY", "Cyprus", ["CY"], ["CYP"], ["Cyprus"]),
    ("CZ", "Czechia", ["CZ"], ["CZE"], ["Czechia"]),
    ("DK", "Denmark", ["DK"], ["DNK"], ["Denmark"]),
    ("DJ", "Djibouti", ["DJ"], ["DJI"], ["Djibouti"]),
    ("DM", "Dominica", ["DM"], ["DMA"], ["Dominica"]),
    ("DO", "Dominican Republic", ["DO"], ["DOM"], ["Dominican Rep."]),
    ("EC", "Ecuador", ["EC"], ["ECU"], ["Ecuador"]),
    ("EG", "Egypt", ["EG"], ["EGY"], ["Egypt"]),
    ("SV", "El Salvador", ["SV"], ["SLV"], ["El Salvador"]),
    ("GQ", "Equatorial Guinea", ["GQ"], ["GNQ"], ["Eq. Guinea"]),
    ("ER", "Eritrea", ["ER"], ["ERI"], ["Eritrea"]),
    ("EE", "Estonia", ["EE"], ["EST"], ["Estonia"]),
    ("SZ", "Eswatini", ["SZ"], ["SWZ"], ["eSwatini"]),
    ("ET", "Ethiopia", ["ET"], ["ETH"], ["Ethiopia"]),
    ("FJ", "Fiji", ["FJ"], ["FJI"], ["Fiji"]),
    ("FI", "Finland", ["FI"], ["FIN"], ["Finland"]),
    ("FR", "France", ["FR"], ["FRA"], ["France"]),
    ("GA", "Gabon", ["GA"], ["GAB"], ["Gabon"]),
    ("GM", "Gambia", ["GM"], ["GMB"], ["Gambia"]),
    ("GE", "Georgia", ["GE"], ["GEO"], ["Georgia"]),
    ("DE", "Germany", ["DE"], ["DEU"], ["Germany"]),
    ("GH", "Ghana", ["GH"], ["GHA"], ["Ghana"]),
    ("GR", "Greece", ["GR"], ["GRC"], ["Greece"]),
    ("GD", "Grenada", ["GD"], ["GRD"], ["Grenada"]),
    ("GT", "Guatemala", ["GT"], ["GTM"], ["Guatemala"]),
    ("GN", "Guinea", ["GN"], ["GIN"], ["Guinea"]),
    ("GW", "Guinea-Bissau", ["GW"], ["GNB"], ["Guinea-Bissau"]),
    ("GY", "Guyana", ["GY"], ["GUY"], ["Guyana"]),
    ("HT", "Haiti", ["HT"], ["HTI"], ["Haiti"]),
    ("HN", "Honduras", ["HN"], ["HND"], ["Honduras"]),
    ("HU", "Hungary", ["HU"], ["HUN"], ["Hungary"]),
    ("IS", "Iceland", ["IS"], ["ISL"], ["Iceland"]),
    ("IN", "India", ["IN"], ["IND"], ["India"]),
    ("ID", "Indonesia", ["ID"], ["IDN"], ["Indonesia"]),
    ("IR", "Iran", ["IR"], ["IRN"], ["Iran"]),
    ("IQ", "Iraq", ["IQ"], ["IRQ"], ["Iraq"]),
    ("IE", "Ireland", ["IE"], ["IRL"], ["Ireland"]),
    ("IL", "Israel", ["IL"], ["ISR"], ["Israel"]),
    ("IT", "Italy", ["IT"], ["ITA"], ["Italy"]),
    ("CI", "Ivory Coast", ["CI"], ["CIV"], ["Cote d'Ivoire", "Côte d'Ivoire"]),
    ("JM", "Jamaica", ["JM"], ["JAM"], ["Jamaica"]),
    ("JP", "Japan", ["JP"], ["JPN"], ["Japan"]),
    ("JO", "Jordan", ["JO"], ["JOR"], ["Jordan"]),
    ("KZ", "Kazakhstan", ["KZ"], ["KAZ"], ["Kazakhstan"]),
    ("KE", "Kenya", ["KE"], ["KEN"], ["Kenya"]),
    ("KI", "Kiribati", ["KI"], ["KIR"], ["Kiribati"]),
    ("KP", "North Korea", ["KP"], ["PRK"], ["North Korea"]),
    ("KR", "South Korea", ["KR"], ["KOR"], ["South Korea"]),
    ("KW", "Kuwait", ["KW"], ["KWT"], ["Kuwait"]),
    ("KG", "Kyrgyzstan", ["KG"], ["KGZ"], ["Kyrgyzstan"]),
    ("LA", "Laos", ["LA"], ["LAO"], ["Laos"]),
    ("LV", "Latvia", ["LV"], ["LVA"], ["Latvia"]),
    ("LB", "Lebanon", ["LB"], ["LBN"], ["Lebanon"]),
    ("LS", "Lesotho", ["LS"], ["LSO"], ["Lesotho"]),
    ("LR", "Liberia", ["LR"], ["LBR"], ["Liberia"]),
    ("LY", "Libya", ["LY"], ["LBY"], ["Libya"]),
    ("LI", "Liechtenstein", ["LI"], ["LIE"], ["Liechtenstein"]),
    ("LT", "Lithuania", ["LT"], ["LTU"], ["Lithuania"]),
    ("LU", "Luxembourg", ["LU"], ["LUX"], ["Luxembourg"]),
    ("MG", "Madagascar", ["MG"], ["MDG"], ["Madagascar"]),
    ("MW", "Malawi", ["MW"], ["MWI"], ["Malawi"]),
    ("MY", "Malaysia", ["MY"], ["MYS"], ["Malaysia"]),
    ("MV", "Maldives", ["MV"], ["MDV"], ["Maldives"]),
    ("ML", "Mali", ["ML"], ["MLI"], ["Mali"]),
    ("MT", "Malta", ["MT"], ["MLT"], ["Malta"]),
    ("MH", "Marshall Islands", ["MH"], ["MHL"], ["Marshall Is."]),
    ("MR", "Mauritania", ["MR"], ["MRT"], ["Mauritania"]),
    ("MU", "Mauritius", ["MU"], ["MUS"], ["Mauritius"]),
    ("MX", "Mexico", ["MX"], ["MEX"], ["Mexico"]),
    ("FM", "Micronesia", ["FM"], ["FSM"], ["Micronesia"]),
    ("MD", "Moldova", ["MD"], ["MDA"], ["Moldova"]),
    ("MC", "Monaco", ["MC"], ["MCO"], ["Monaco"]),
    ("MN", "Mongolia", ["MN"], ["MNG"], ["Mongolia"]),
    ("ME", "Montenegro", ["ME"], ["MNE"], ["Montenegro"]),
    ("MA", "Morocco", ["MA"], ["MAR"], ["Morocco"]),
    ("MZ", "Mozambique", ["MZ"], ["MOZ"], ["Mozambique"]),
    ("MM", "Myanmar", ["MM"], ["MMR"], ["Myanmar"]),
    ("NA", "Namibia", ["NA"], ["NAM"], ["Namibia"]),
    ("NR", "Nauru", ["NR"], ["NRU"], ["Nauru"]),
    ("NP", "Nepal", ["NP"], ["NPL"], ["Nepal"]),
    ("NL", "Netherlands", ["NL"], ["NLD"], ["Netherlands"]),
    ("NZ", "New Zealand", ["NZ"], ["NZL"], ["New Zealand"]),
    ("NI", "Nicaragua", ["NI"], ["NIC"], ["Nicaragua"]),
    ("NE", "Niger", ["NE"], ["NER"], ["Niger"]),
    ("NG", "Nigeria", ["NG"], ["NGA"], ["Nigeria"]),
    ("MK", "North Macedonia", ["MK"], ["MKD"], ["North Macedonia"]),
    ("NO", "Norway", ["NO"], ["NOR"], ["Norway"]),
    ("OM", "Oman", ["OM"], ["OMN"], ["Oman"]),
    ("PK", "Pakistan", ["PK"], ["PAK"], ["Pakistan"]),
    ("PW", "Palau", ["PW"], ["PLW"], ["Palau"]),
    ("PA", "Panama", ["PA"], ["PAN"], ["Panama"]),
    ("PG", "Papua New Guinea", ["PG"], ["PNG"], ["Papua New Guinea"]),
    ("PY", "Paraguay", ["PY"], ["PRY"], ["Paraguay"]),
    ("PE", "Peru", ["PE"], ["PER"], ["Peru"]),
    ("PH", "Philippines", ["PH"], ["PHL"], ["Philippines"]),
    ("PL", "Poland", ["PL"], ["POL"], ["Poland"]),
    ("PT", "Portugal", ["PT"], ["PRT"], ["Portugal"]),
    ("QA", "Qatar", ["QA"], ["QAT"], ["Qatar"]),
    ("RO", "Romania", ["RO"], ["ROU"], ["Romania"]),
    ("RU", "Russia", ["RU"], ["RUS"], ["Russia"]),
    ("RW", "Rwanda", ["RW"], ["RWA"], ["Rwanda"]),
    ("KN", "Saint Kitts and Nevis", ["KN"], ["KNA"], ["St. Kitts and Nevis"]),
    ("LC", "Saint Lucia", ["LC"], ["LCA"], ["Saint Lucia"]),
    ("VC", "Saint Vincent and the Grenadines", ["VC"], ["VCT"], ["St. Vin. and Gren."]),
    ("WS", "Samoa", ["WS"], ["WSM"], ["Samoa"]),
    ("SM", "San Marino", ["SM"], ["SMR"], ["San Marino"]),
    ("ST", "Sao Tome and Principe", ["ST"], ["STP"], ["São Tomé and Principe"]),
    ("SA", "Saudi Arabia", ["SA"], ["SAU"], ["Saudi Arabia"]),
    ("SN", "Senegal", ["SN"], ["SEN"], ["Senegal"]),
    ("RS", "Serbia", ["RS"], ["SRB"], ["Serbia"]),
    ("SC", "Seychelles", ["SC"], ["SYC"], ["Seychelles"]),
    ("SL", "Sierra Leone", ["SL"], ["SLE"], ["Sierra Leone"]),
    ("SG", "Singapore", ["SG"], ["SGP"], ["Singapore"]),
    ("SK", "Slovakia", ["SK"], ["SVK"], ["Slovakia"]),
    ("SI", "Slovenia", ["SI"], ["SVN"], ["Slovenia"]),
    ("SB", "Solomon Islands", ["SB"], ["SLB"], ["Solomon Is."]),
    ("SO", "Somalia", ["SO"], ["SOM"], ["Somalia"]),
    ("ZA", "South Africa", ["ZA"], ["ZAF"], ["South Africa"]),
    ("SS", "South Sudan", ["SS"], ["SSD"], ["S. Sudan"]),
    ("ES", "Spain", ["ES"], ["ESP"], ["Spain"]),
    ("LK", "Sri Lanka", ["LK"], ["LKA"], ["Sri Lanka"]),
    ("SD", "Sudan", ["SD"], ["SDN"], ["Sudan"]),
    ("SR", "Suriname", ["SR"], ["SUR"], ["Suriname"]),
    ("SE", "Sweden", ["SE"], ["SWE"], ["Sweden"]),
    ("CH", "Switzerland", ["CH"], ["CHE"], ["Switzerland"]),
    ("SY", "Syria", ["SY"], ["SYR"], ["Syria"]),
    ("TJ", "Tajikistan", ["TJ"], ["TJK"], ["Tajikistan"]),
    ("TZ", "Tanzania", ["TZ"], ["TZA"], ["Tanzania"]),
    ("TH", "Thailand", ["TH"], ["THA"], ["Thailand"]),
    ("TL", "Timor-Leste", ["TL"], ["TLS"], ["Timor-Leste"]),
    ("TG", "Togo", ["TG"], ["TGO"], ["Togo"]),
    ("TO", "Tonga", ["TO"], ["TON"], ["Tonga"]),
    ("TT", "Trinidad and Tobago", ["TT"], ["TTO"], ["Trinidad and Tobago"]),
    ("TN", "Tunisia", ["TN"], ["TUN"], ["Tunisia"]),
    ("TR", "Turkey", ["TR"], ["TUR"], ["Turkey"]),
    ("TM", "Turkmenistan", ["TM"], ["TKM"], ["Turkmenistan"]),
    ("TV", "Tuvalu", ["TV"], ["TUV"], ["Tuvalu"]),
    ("UG", "Uganda", ["UG"], ["UGA"], ["Uganda"]),
    ("UA", "Ukraine", ["UA"], ["UKR"], ["Ukraine"]),
    ("AE", "United Arab Emirates", ["AE"], ["ARE"], ["United Arab Emirates"]),
    ("GB", "United Kingdom", ["GB"], ["GBR"], ["United Kingdom"]),
    ("US", "United States", ["US"], ["USA"], ["United States of America"]),
    ("UY", "Uruguay", ["UY"], ["URY"], ["Uruguay"]),
    ("UZ", "Uzbekistan", ["UZ"], ["UZB"], ["Uzbekistan"]),
    ("VU", "Vanuatu", ["VU"], ["VUT"], ["Vanuatu"]),
    ("VA", "Vatican City", ["VA"], ["VAT"], ["Vatican"]),
    ("VE", "Venezuela", ["VE"], ["VEN"], ["Venezuela"]),
    ("VN", "Vietnam", ["VN"], ["VNM"], ["Vietnam"]),
    ("YE", "Yemen", ["YE"], ["YEM"], ["Yemen"]),
    ("ZM", "Zambia", ["ZM"], ["ZMB"], ["Zambia"]),
    ("ZW", "Zimbabwe", ["ZW"], ["ZWE"], ["Zimbabwe"]),
    # Specials / disputed / map units
    ("TW", "Taiwan", ["TW"], ["TWN"], ["Taiwan"]),
    ("XK", "Kosovo", ["XK"], ["KOS", "XKX"], ["Kosovo"]),
    ("PS", "Palestine", ["PS"], ["PSE"], ["Palestine"]),
    ("EH", "Western Sahara", ["EH"], ["ESH", "SAH"], ["W. Sahara", "Western Sahara"]),
    ("GL", "Greenland", ["GL"], ["GRL"], ["Greenland"]),
    ("AQ", "Antarctica", ["AQ"], ["ATA"], ["Antarctica"]),
    ("HK", "Hong Kong", ["HK"], ["HKG"], ["Hong Kong"]),
    ("MO", "Macau", ["MO"], ["MAC"], ["Macao"]),
    ("PR", "Puerto Rico", ["PR"], ["PRI"], ["Puerto Rico"]),
    ("NC", "New Caledonia", ["NC"], ["NCL"], ["New Caledonia"]),
    ("PF", "French Polynesia", ["PF"], ["PYF"], ["Fr. Polynesia"]),
    ("FK", "Falkland Islands", ["FK"], ["FLK"], ["Falkland Is."]),
    ("FO", "Faroe Islands", ["FO"], ["FRO"], ["Faeroe Islands"]),
    ("BM", "Bermuda", ["BM"], ["BMU"], ["Bermuda"]),
    ("NCYP", "Northern Cyprus", [], ["CYN"], ["N. Cyprus"]),
    ("SML", "Somaliland", [], ["SOL"], ["Somaliland"]),
]


def main() -> None:
    out = []
    for cid, name, iso, adm, names in COUNTRIES:
        if cid == "XK":
            emoji = "\U0001f1fd\U0001f1f0"
        elif iso and len(iso[0]) == 2 and iso[0].isalpha():
            emoji = flag(iso[0])
        else:
            emoji = "\U0001f3f3\ufe0f"
        out.append(
            {
                "id": cid,
                "name": name,
                "emoji": emoji,
                "ne_iso_a2": list(iso),
                "ne_adm0_a3": list(adm),
                "ne_names": list(names),
            }
        )

    path = Path(__file__).resolve().parent.parent / "data" / "countries.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps({"countries": out}, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {len(out)} countries to {path}")


if __name__ == "__main__":
    main()
